dist: bionic
os: linux

language: node_js
node_js:
  - '12'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g codecov

script:
  - ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - codecov
  - ng build